name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d34e84af2896b4f7a178 # v4
        with:
          node-version: "20"
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 600000

      - name: Build app
        run: yarn build:app:docker

      - name: Add SPA fallback for deep links
        run: cp excalidraw-app/build/index.html excalidraw-app/build/404.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74203658a474abb16af2bc7e1eb5edd # v3
        with:
          path: excalidraw-app/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b4aed7e9abb843e3c2f03b # v4
